apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-feedback-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-feedback-service
  template:
    metadata:
      labels:
        app: go-feedback-service
    spec:
      containers:
        - name: go-feedback-service
          image: 008496666795.dkr.ecr.us-east-1.amazonaws.com/go-feedback-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
