apiVersion: v1
kind: Service
metadata:
  name: go-feedback-service
spec:
  type: NodePort
  selector:
    app: go-feedback-service 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
